.\" $Id$
.TH cul "5" "May 2004" "cul 0.1.0" DFW
.SH "NAME"
cul \- consult file format for
computer intelligence
disassembler 386
.SH "DESCRIPTION"
\fBcul\fR files are generally used as the second argument for
\fB\cidis\fR\.
.br
On top of the user commands described in this page,
the full assembler is available after the command ASSEMBLER and
the full Forth language is available after the command FORTH .

.SH "SYNTAX"
The syntax in the following applies to the cul file,
but these commands can be used interactively too.

.SH "COMMENT"
A backslash \\ followed by a space ignores the remainder of a line.
A open bracket ( followed by a space ignores the remainder of the file
until a closing bracket (so don't use in expressions!).
Comment signs are not recognized within strings.
The string symbol `` " '' is not recognized within comment.

.SH "EXPRESSIONS"
An arithmetic atom can be a number, a character or a label.
The default number base is hexadecimal,
but this can be overruled by the # prefix for decimal.
A character is denoted by a & prefix.
A label must be previously defined by an EQU or LABEL statement.
Hexadecimal numbers can start in a letter,
and labels can be fully numeric,
but both practices are discouraged.
.br
An arithmetic expression combines atom's and the operators
+ - / * MOD in a postfix fashion.
Brackets are not allowed (nor needed).
.br
A string is delimited by double quotes: " .
It may contain embedded new lines.
It can contain double quotes,
by doubling them.
.br
A range consist of two atoms, representing addressing in the
host space, i.e. such as seen during execution.
Ranges are exclusive, but they are always expanded to contain
at least one byte.
.br
A name cannot contains spaces.
.SH "KEYWORDS"
Keywords (or words in Forth parlance) apply to one or more
preceeding expressions.
They may also scan ahead,
mostly for a name that is hence-to-forth known, e.g. as a label.
.TP
<expr> LABEL "name"
.br
Add "name" to the plain labels with value <expr>.
.TP
<expr> EQU "name"
.br
Add "name" to the plain labels with value <expr>.
.TP
<expr1> <expr2> -DB: "name"
.br
The range <expr1> <expr2> is hence-to-forth known by
"name" and is a section to be disassembled as byte values.
.TP
<expr1> <expr2> -DW: "name"
.br
The range <expr1> <expr2> is hence-to-forth known by
"name" and is a section to be disassembled as word (16-bit)
values.
.TP
<expr1> <expr2> -DL: "name"
.br
The range <expr1> <expr2> is hence-to-forth known by
"name" and is a section to be disassembled as long (32-bit) values.
.TP
<expr1> <expr2> -DC16: "name"
.br
The range <expr1> <expr2> is hence-to-forth known by
"name" and is a section to be disassembled as a 16-bit code section.
This command is specific to the Intel 80386.
.TP
<expr1> <expr2> -DC: "name"
.br
The range <expr1> <expr2> is hence-to-forth known by
"name" and is a section to be disassembled as a normal code section.
For the Intel 80386 this means a 32-bit code section.
.TP
<expr1> <expr2> [-DB-|-BW-|-DL-|-DC-|-DC16-]
These commands are equivalent to -DB: -DW: -DL: -DC: -DC16: but the
sections are anonymous.
.TP
<expr> -ORG-
.br
The start of the code buffer is associated with the target address
<expr>.
.TP
<string> COMMENT
.br
The string is a comment associated with the target address
<expr>.
It will be a separate line or lines in front of the disassembly.
.TP
<expr> COMMENT: "comment"
.br
The remainder of the line is a comment associated with the target address
<expr>.
It will be printed after the disassembly on the same line.
.TP
DISASSEMBLE-ALL
.br
Disassemble the code buffer using all available information.
.TP
SORT-ALL
.br
Sort all available information on the addresses it applies to.
This is mandatory for DISASSEMBLE-ALL and recommended for DUMP-ALL .
.TP
DUMP-ALL
.br
Output all available information to standard output.
This includes all information added interactively.
.TP
INCLUDE "name"
.br
Read in the file named "name" and execute all commands there in.
.TP
[PLAIN-LABELS|SECTION-LABELS] REMOVE: "name"
.br
Select the plain labels or the sections labels class and
remove the label "name" from it.
Removal of several labels in the same class need not repeat
the selection.
.br
When redefining a label is intended,
the old label must be removed first.
.TP
<expr> CRAWL
.br
Use the information that <expr> is a target code address.
Heuristically find as much code as possible by disassembling
from this address up till an unconditional transfer of control,
and assuming jumps refer to more code addresses.
Add new knowledge to the labeled sections,
then combine any anonymous sections.
.TP

.SH "ADVANCED"
With the Forth commands DUP SWAP OVER 2DUP 2SWAP 2OVER
writing down the same <expr> repeatedly can be avoided.
See lina(1) if installed.
.br
A sequence of commands can be combined into a macro in the following
fashion (which is regular Forth practice):
.br
\fB : "name" <sequence> ;\fR
.br
Using "name" will result in the execution of the commands in <sequence>.
If <sequence> contains commands that scan ahead,
the scanning will be done when "name" is invoked;
this can be confusing for novices.
.TP
SHOW-REGISTER
.br
List the names of all registered objects of the class labels.
A class can be made current by typing its name
and then its content can be
printed using .LABELS .

.SH "COMMAND"

After the command \fBASSEMBLER\fR ,
all assembler commands can be tried
out interactively (see lina(1)).

After the command \fBFORTH\fR
you have a full Forth environment available (see lina(1))

A \fBBYE\fR command ends an interactive session.

.SH "AVAILABILITY"
\ficias/cdis\fR is based on \fBciforth\fR.
.br
The generic system can be fetched from
.IP
\fI http://home.hccnet.nl/a.w.m.van.der.horst/ciforth.html\fR
.PP
MS-DOS, "windows" , stand alone and Alpha Linux
binary versions are available.

.SH "EXAMPLE"
A typical consult file to disassemble
a c-program could contain:
.br
 \ \ \ 100 148 -   -ORG-
.br
 \ \ \ 0 148 -DB: header
.br
 \ \ \ 148 COMMENT: entry point
.br
 \ \ \ 148 2008 -DB : text
.br
 \ \ \ 2008 4804 -DC: data
.br
 \ \ \ DISASSEMBLE-ALL
.br
 \ \ \ BYE
.br
The actual command to disassemble is:
.br
 \ \ \ cidis freecell.exe freecell.cul > freecell.asm

.SH "SEE ALSO"

cias(1) computer_intelligence_assembler_386
.br
cidis(1) computer_intelligence_disassembler_386
.br
lina(1) Linux Native version of ciforth.

.SH "CAVEAT"
Mistakes in Forth mode can easily crash \ficias/cdis\fR.

\ficias/cdis\fR is case sensitive.

.SH "AUTHOR"
Copyright \(co 2004
Albert van der Horst \fI albert@spenarnc.xs4all.nl\fR.
\fIcias/cidis\fR
are made available under the GNU Public License:
quality, but NO warranty.
